name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Running Node Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # Test on multiple Node.js versions

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Start the server in the background
      - name: Start server
        run: node server.js &
        env:
          PORT: 5000 # Ensure the server uses the correct port

      # Run tests
      - name: Run tests
        run: npm test

      # Stop the server after tests
      - name: Stop server
        run: kill $(lsof -t -i:5000) # Kill the process using port 5000
